# name: Test Python Input

# on:
   
#    workflow_dispatch:
#      inputs:
#        myInput:
#          description: 'User Input:'
#          required: true
#          default: "Hello World"


# env:


     

# jobs:
#   run-python-test:
#     runs-on: ubuntu-latest
#     steps:
  
#       - name: Checkout
#         uses: actions/checkout@v2.3.4
  
#       - name: Setup Python
#         uses: actions/setup-python@v2.2.2
#         with:
#           python-version: 3.8
  
#       - name: Execute Test Script
#         run: |
#           echo "Store: ${{ github.event.inputs.myInput }}"
#           INPUT_STORE=${{ github.event.inputs.myInput }} python3 scripts/test.py

name: AMAR WORKFLOW

on:
  

  workflow_dispatch:
    inputs:
      ValueA:
        description: 'First Name'
        required: true
        default: '--'
        
        

      ValueB:
        description: 'Last Name'
        required: true
        default: '--'
        
        

  
jobs:
  run-python-test:
    runs-on: ubuntu-latest
    steps:
  
      - name: Checkout
        uses: actions/checkout@v2.3.4
        
  
      - name: Setup Python
        uses: actions/setup-python@v2.2.2
        with:
          python-version: 3.8
  
      - name: Execute Test Script
        run: INPUT_STORE=${{ github.event.inputs.ValueA }},${{ github.event.inputs.ValueB }} python3 scripts/test.py


      
      
      
            
   
    